os:
  - linux
  - osx
osx_image: xcode8.3
dist: trusty
sudo: required
language: swift
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - swift build
  - swift build -c release
after_success:
  - bash <(curl -s https://codecov.io/bash) -t "d29672e4-6a60-4e89-8922-65bb738fcffb"
